version: '3'

services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - ${DATA_DIR:-./data/db}:/data/db
  ubuntu:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
     - "6100:6100"
    depends_on:
      - mongodb

